### ISSUE TITLE
An error occurred while creating a new patient: AppwriteException [Error]: Invalid document structure: Unknown attribute: "identificationDocumentId"

### ISSUE THREAD

**Issue by Sharmin097** [adrianhajdin/healthcare#56]
An error occurred while creating a new patient: AppwriteException [Error]: Invalid document structure: Unknown attribute: "identificationDocumentId"
how to solve this one .it happens  in the registration form

**Comment by cademy07** [comment]
The same I encountered this error 
`POST /patients/67583a690025433d01bb/register 200 in 6111ms
An error occurred while creating a new patient: AppwriteException [Error]: Invalid document structure: Unknown attribute: "identificationDocumentId"
    at Client.call (webpack-internal:///(rsc)/./node_modules/node-appwrite/lib/client.js:206:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Databases.createDocument (webpack-internal:///(rsc)/./node_modules/node-appwrite/lib/services/databases.js:1711:16)
    at async $$ACTION_2 (webpack-internal:///(rsc)/./lib/actions/patient.actions.ts:66:28)
    at async C:\Users\User\Documents\React-NextJs\healthcare\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:39:418
    at async rS (C:\Users\User\Documents\React-NextJs\healthcare\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:38:7978)    
    at async r2 (C:\Users\User\Documents\React-NextJs\healthcare\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:41:1251)    
    at async doRender (C:\Users\User\Documents\React-NextJs\healthcare\node_modules\next\dist\server\base-server.js:1438:30)
    at async cacheEntry.responseCache.get.routeKind (C:\Users\User\Documents\React-NextJs\healthcare\node_modules\next\dist\server\base-server.js:1587:40)
    at async DevServer.renderToResponseWithComponentsImpl (C:\Users\User\Documents\React-NextJs\healthcare\node_modules\next\dist\server\base-server.js:1507:28)
    at async DevServer.renderPageComponent (C:\Users\User\Documents\React-NextJs\healthcare\node_modules\next\dist\server\base-server.js:1924:24)
    at async DevServer.renderToResponseImpl (C:\Users\User\Documents\React-NextJs\healthcare\node_modules\next\dist\server\base-server.js:1962:32)
    at async DevServer.pipeImpl (C:\Users\User\Documents\React-NextJs\healthcare\node_modules\next\dist\server\base-server.js:920:25)
    at async NextNodeServer.handleCatchallRenderRequest (C:\Users\User\Documents\React-NextJs\healthcare\node_modules\next\dist\server\next-server.js:272:17)
    at async DevServer.handleRequestImpl (C:\Users\User\Documents\React-NextJs\healthcare\node_modules\next\dist\server\base-server.js:816:17)   
    at async C:\Users\User\Documents\React-NextJs\healthcare\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (C:\Users\User\Documents\React-NextJs\healthcare\node_modules\next\dist\trace\trace.js:154:20)
    at async DevServer.handleRequest (C:\Users\User\Documents\React-NextJs\healthcare\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
    at async invokeRender (C:\Users\User\Documents\React-NextJs\healthcare\node_modules\next\dist\server\lib\router-server.js:174:21)
    at async handleRequest (C:\Users\User\Documents\React-NextJs\healthcare\node_modules\next\dist\server\lib\router-server.js:353:24)
    at async requestHandlerImpl (C:\Users\User\Documents\React-NextJs\healthcare\node_modules\next\dist\server\lib\router-server.js:377:13)      
    at async Server.requestListener (C:\Users\User\Documents\React-NextJs\healthcare\node_modules\next\dist\server\lib\start-server.js:141:13) { 
  code: 400,
  type: 'document_invalid_structure',
  response: {
    message: 'Invalid document structure: Unknown attribute: "identificationDocumentId"',
    code: 400,
    type: 'document_invalid_structure',
    version: '1.6.1'
  }
}`

**Comment by Sharmin097** [comment]
Hi, please check spelling and all properties  of all attributes as  I made
a mistake in spelling and properties
